# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-03 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handyhelper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_adder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_jobs', to='handyhelper.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_doer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_list', to='handyhelper.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_adder',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_doer',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
